### ISSUE TITLE
Rails 7.0 update

### ISSUE THREAD

**Issue by pulgamecanica** [fakenine/omniauth-marvin#5]
Since Rails > 7.0.0 the link_to helper method changed on the last Rails update.
The method to be called is now passed through **data**.

So insead of:
`<%= link_to "Sign out", destroy_user_session_path, method: :delete if curreconsidernt_user %>`
now it's
`<%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete } if current_user %>`
I was thinking it would be nice to update the README to consider the newer version of rails :)

**Comment by pulgamecanica** [comment]
I will close this issue because it's not really an issue but I wanted to mention this hehe

**Comment by jgengo** [comment]
Done https://github.com/fakenine/omniauth-marvin/pull/6

**Comment by fakenine** [comment]
@jgengo @pulgamecanica Thank you for the info!
